# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      ../core/boot.nix
      ../core/drivers/nvidia.nix
      ../configuration.nix
    ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];

    fileSystems = {
      "/" = {
        device = "/dev/disk/by-uuid/e9d29fb0-4b79-4f43-9652-9d9fe052c1aa";
        fsType = "ext4";
      };
      "/boot/efi" = {
        device = "/dev/disk/by-uuid/0162-22F2";
        fsType = "vfat";
      };
      "/home/hd1" = {
        device = "/dev/sda1";
        fsType = "ext4";
      };
      "/home/ssd1" = {
        device = "/dev/sdb1";
        fsType = "ext4";
      };
    };

    swapDevices = [ ];
  };

  networking = {
    useDHCP = lib.mkDefault true;
    hostName = "EVA-01";
  };

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    video.hidpi.enable = lib.mkDefault true;
  };

  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.utf8";
  system.stateVersion = "unstable";
}
