{ config, pkgs, ... }:

{
  programs.neovim = {
    enable = true;
    defaultEditor = true;

    plugins = with pkgs.vimPlugins; [
      tokyonight-nvim
    ]

    generatedConfigs = {
      lua = ''
        -- Generated by home-manager
        vim.cmd [[ colorscheme tokyonight-night ]]
      '';
    }
  }
}
